trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/build.ps1'
    arguments: >
      --target Distribute
      --configuration $(buildConfiguration)
      --coverage-format cobertura

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/.coverage/cobertura.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/source'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'artifacts'
    Contents: '*.exe'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'